// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azxwyegdldxcikjzfbeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6eHd5ZWdkbGR4Y2lranpmYmV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjgzMTYsImV4cCI6MjA3MzU0NDMxNn0.7IBBYreR7xVSWSrA4Wt8tHSLQOwzZMWjmWa4oGZbDkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});