// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdunjstnnaihhxfouhrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkdW5qc3RubmFpaGh4Zm91aHJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODE0NjIsImV4cCI6MjA3Mzc1NzQ2Mn0.oBjndEDgOWUg2UxVoINrvci_u38ltSDxMOfpUjVcT2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});